export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const EDITA_PROJETO = 'EDITA_PROJETO'
export const EXCLUI_PROJETO = 'EXCLUIR_PROJETO'
export const DEFINIR_PROJETO = 'DEFINIR_PROJETO'

export const NOTIFICAR = 'NOTIFICAR'

export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS'
export const ADICIONA_TAREFA = 'ADICIONA_TAREFA'
export const EDITA_TAREFA = 'EDITA_TAREFA'

